using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using PdfEditorApp.Plugins.CSharpEditor.Models;

namespace PdfEditorApp.Plugins.CSharpEditor.Services;

/// <summary>
/// Service responsible for exporting scripts and notebooks into standard developer formats
/// (.cs standalone files, .csx Roslyn scripts, .ipynb Jupyter notebooks, and .md Markdown documents).
/// </summary>
public static class DocumentExportService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    /// <summary>
    /// Exports a script into a clean standalone C# (.cs) source code file.
    /// </summary>
    public static string ExportScriptToCs(ScriptDocumentItem script)
    {
        ArgumentNullException.ThrowIfNull(script);

        var sb = new StringBuilder();
        sb.AppendLine("// ------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     This code was exported from FryPDF C# Code Studio.");
        sb.AppendLine($"//     Script: {script.Title}");
        sb.AppendLine($"//     Exported: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// ------------------------------------------------------------------------------");
        sb.AppendLine();

        if (script.References?.Count > 0)
        {
            sb.AppendLine("// Required Package References:");
            foreach (var r in script.References)
            {
                sb.AppendLine($"//   - {r}");
            }
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(script.Notes))
        {
            sb.AppendLine("/*");
            sb.AppendLine(" * Notes & Documentation:");
            foreach (var line in script.Notes.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None))
            {
                sb.AppendLine($" * {line}");
            }
            sb.AppendLine(" */");
            sb.AppendLine();
        }

        sb.Append(script.Code ?? string.Empty);
        if (!sb.ToString().EndsWith("\n")) sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Exports a script into a C# Script (.csx) format compatible with dotnet-script and csi.
    /// </summary>
    public static string ExportScriptToCsx(ScriptDocumentItem script)
    {
        ArgumentNullException.ThrowIfNull(script);

        var sb = new StringBuilder();
        sb.AppendLine($"// C# Script (.csx): {script.Title}");
        sb.AppendLine();

        if (script.References?.Count > 0)
        {
            foreach (var r in script.References)
            {
                if (r.StartsWith("#r", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine(r);
                }
                else if (r.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"#r \"{r}\"");
                }
                else
                {
                    sb.AppendLine($"#r \"nuget: {r}\"");
                }
            }
            sb.AppendLine();
        }

        sb.Append(script.Code ?? string.Empty);
        if (!sb.ToString().EndsWith("\n")) sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Exports an interactive notebook into standard Jupyter Notebook (.ipynb) v4 schema format.
    /// Compatible with VS Code, JupyterLab, and GitHub notebook renderers.
    /// </summary>
    public static string ExportNotebookToIpynb(NotebookDocumentItem notebook)
    {
        ArgumentNullException.ThrowIfNull(notebook);

        var cells = new List<object>();

        foreach (var cell in notebook.Cells)
        {
            var sourceLines = SplitToLinesWithNewlines(cell.Source);

            if (cell.Type == CellType.Markdown)
            {
                cells.Add(new
                {
                    cell_type = "markdown",
                    metadata = new Dictionary<string, object>(),
                    source = sourceLines
                });
            }
            else
            {
                var outputs = new List<object>();
                if (!string.IsNullOrEmpty(cell.OutputText))
                {
                    outputs.Add(new
                    {
                        output_type = "stream",
                        name = cell.HasError ? "stderr" : "stdout",
                        text = SplitToLinesWithNewlines(cell.OutputText)
                    });
                }

                cells.Add(new
                {
                    cell_type = "code",
                    execution_count = cell.ExecutionCount,
                    metadata = new Dictionary<string, object>(),
                    outputs = outputs,
                    source = sourceLines
                });
            }
        }

        var ipynbObj = new
        {
            cells = cells,
            metadata = new
            {
                language_info = new
                {
                    name = "csharp",
                    version = "13.0",
                    file_extension = ".cs",
                    mimetype = "text/x-csharp"
                },
                kernelspec = new
                {
                    name = ".net-csharp",
                    display_name = ".NET (C#)",
                    language = "C#"
                }
            },
            nbformat = 4,
            nbformat_minor = 5
        };

        return JsonSerializer.Serialize(ipynbObj, JsonOptions);
    }

    /// <summary>
    /// Exports an interactive notebook into clean GitHub-Flavored Markdown (.md).
    /// </summary>
    public static string ExportNotebookToMarkdown(NotebookDocumentItem notebook)
    {
        ArgumentNullException.ThrowIfNull(notebook);

        var sb = new StringBuilder();
        sb.AppendLine($"# {notebook.Title}");
        if (!string.IsNullOrWhiteSpace(notebook.Description))
        {
            sb.AppendLine();
            sb.AppendLine(notebook.Description);
        }
        sb.AppendLine();
        sb.AppendLine($"*Exported from FryPDF C# Code Studio • {DateTime.UtcNow:yyyy-MM-dd}*");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();

        int cellNum = 1;
        foreach (var cell in notebook.Cells)
        {
            if (cell.Type == CellType.Markdown)
            {
                sb.AppendLine(cell.Source ?? string.Empty);
                sb.AppendLine();
            }
            else
            {
                var countBadge = cell.ExecutionCount.HasValue ? $"[{cell.ExecutionCount.Value}]" : $"[{cellNum}]";
                sb.AppendLine($"### Cell {countBadge} (C#)");
                sb.AppendLine("```csharp");
                sb.AppendLine(cell.Source ?? string.Empty);
                sb.AppendLine("```");

                if (!string.IsNullOrWhiteSpace(cell.OutputText))
                {
                    sb.AppendLine();
                    sb.AppendLine("<details open><summary><b>Output</b></summary>");
                    sb.AppendLine();
                    sb.AppendLine("```output");
                    sb.AppendLine(cell.OutputText);
                    sb.AppendLine("```");
                    sb.AppendLine("</details>");
                    sb.AppendLine();
                }

                sb.AppendLine();
            }
            cellNum++;
        }

        return sb.ToString();
    }

    private static string[] SplitToLinesWithNewlines(string? text)
    {
        if (string.IsNullOrEmpty(text)) return Array.Empty<string>();

        var rawLines = text.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        var result = new string[rawLines.Length];
        for (int i = 0; i < rawLines.Length; i++)
        {
            // In Jupyter .ipynb format, each line except possibly the last ends with '\n'
            result[i] = i < rawLines.Length - 1 ? rawLines[i] + "\n" : rawLines[i];
        }
        return result;
    }
}
